import { Inter } from "next/font/google";
import GlobalNav from "../ui/grobalNav.jsx";
import styles from "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Conduit",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body>
                <GlobalNav />
                {children}
            </body>
        </html>
    );
}
